controller:
  kind: DaemonSet
  hostPort:
    enabled: true
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
  service:
    type: NodePort
  publishService:
    enabled: false
  nodeSelector:
    ingress-ready: "true"
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
