grafana:
  enabled: true
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorNamespaceSelector: {}
    ruleSelector: {}
    ruleSelectorNilUsesHelmValues: false
    ruleNamespaceSelector: {}
    scrapeConfigSelector: {}
    scrapeConfigSelectorNilUsesHelmValues: false
    scrapeConfigNamespaceSelector: {}
alertmanager:
  enabled: true
